title: Don Pollack
baseurl: ""

defaults:
  - scope:
      path: ""
    values:
      layout: default

  - scope:
      path: /assets/images
    values:
      image: true

  - scope:
      path: /assets/images/home/thumbnails
    values:
      image: true
      home-thumbnail: true

