backend:
  name: git-gateway
  branch: main

site_url: "https://www.donpollack.com"
media_folder: "static/uploads"

collections:
  - name: "news"
    label: "News and Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", default: "text", widget: hidden}
      - {label: "Title", name: "title", widget: string}
      - {label: "Publish Date", name: "date", widget: datetime}
      - {label: "Body", name: "body", widget: markdown}

  - name: "data"
    label: "Site Data"
    files:
      - label: "Home Page Data"
        name: "home"
        file: "index.html"
        fields:
          - {label: "Title", name: "title", widget: string}

      - label: "Home Page Images"
        name: "home-images"
        file: "_data/home-images.yml"
        fields:
          - label: "Home Page Images"
            name: "items"
            widget: list
            fields:
              - {label: "Title", name: "title", widget: string}
              - {label: "Heading", name: "heading", widget: string}
              - {label: "Image", name: "image", widget: image}
              - {label: "File Link", name: "link", widget: file}
              - {label: "Caption", name: "caption", widget: string}
              - {label: "Material", name: "material", widget: string}
              - {label: "Size", name: "size", widget: string}
              - label: "Slideshow"
                name: "slideshow"
                widget: object
                fields:
                  - {label: "Name", name: "name", widget: string}
                  - label: "Images"
                    name: "images"
                    widget: list
                    fields:
                      - {label: "Image", name: "image", widget: image}

      - label: "Galleries"
        name: "galleries"
        file: "_data/galleries.yml"
        fields:
          - label: "Galleries"
            name: "items"
            widget: list
            fields:
              - {label: "Name", name: "name", widget: string}
              - {label: "Link", name: "link", widget: string}

      - label: "Navigation"
        name: "navigation"
        file: "_data/navigation.yml"
        fields:
          - label: "Navigation"
            name: "items"
            widget: list
            fields:
              - {label: "Name", name: "name", widget: string}
              - {label: "Link", name: "link", widget: string}

      - label: "Documents"
        name: "documents"
        file: "_data/documents.yml"
        fields:
          - label: "Documents"
            name: "items"
            widget: list
            fields:
              - {label: "Title", name: "title", widget: string}
              - {label: "Document Thumbnail", name: "image", widget: image}
              - {label: "Document", name: "document", widget: file}
