backend:
  name: git-gateway
  branch: master

media_folder: "assets/images/uploads"

collections:
  - name: "news"
    label: "News"
    folder: "_posts"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "text"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
