backend:
  name: git-gateway
  branch: master

media_folder: "assets/images"

collections:
  - name: "news"
    label: "News"
    folder: "_posts"
    create: true
    fields:
      - {label: "Layout", name: "layout", default: "text", widget: hidden}
      - {label: "Title", name: "title", widget: string}
      - {label: "Publish Date", name: "date", widget: datetime}
      - {label: "Body", name: "body", widget: markdown}
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "index.html"
        fields:
          - label: "Title"
            name: "title"
            widget: string
          - label: "Images"
            name: "images"
            file: "_data/home-images.yml"
            widget: list
            fields:
              - {label: "Title", name: "title", widget: string}
              - {label: "Image File", name: "image", widget: string}
              - {label: "Caption", name: "caption", widget: string}
              - {label: "Material", name: "material", widget: string}
              - {label: "Size", name: "size", widget: string}
          - label: "Images (Test)"
            name: "images-test"
            file: "home-images.yml"
            widget: list
            fields:
              - {label: "Title", name: "title", widget: string}
              - {label: "Image File", name: "image", widget: string}
              - {label: "Caption", name: "caption", widget: string}
              - {label: "Material", name: "material", widget: string}
              - {label: "Size", name: "size", widget: string}
      - label: "Home Images (Test)"
        name: "home-images"
        file: "_data/home-images.yml"
        fields:
          - label: "Images"
            name: "images-test"
            widget: list
            fields:
              - {label: "Title", name: "title", widget: string}
              - {label: "Image File", name: "image", widget: string}
              - {label: "Caption", name: "caption", widget: string}
              - {label: "Material", name: "material", widget: string}
              - {label: "Size", name: "size", widget: string}
      - label: "Home Images (Test 2)"
        name: "home-images-2"
        file: "home-images.yml"
        fields:
          - label: "Images"
            name: "images-test"
            widget: list
            fields:
              - {label: "Title", name: "title", widget: string}
              - {label: "Image File", name: "image", widget: string}
              - {label: "Caption", name: "caption", widget: string}
              - {label: "Material", name: "material", widget: string}
              - {label: "Size", name: "size", widget: string}
