backend:
  name: git-gateway
  branch: master

media_folder: "assets/images"

collections:
  - name: "news"
    label: "News"
    folder: "_posts"
    create: true
    fields:
      - {label: "Layout", name: "layout", default: "text", widget: hidden}
      - {label: "Title", name: "title", widget: string}
      - {label: "Publish Date", name: "date", widget: datetime}
      - {label: "Body", name: "body", widget: markdown}
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "inded"
        file: "index.html"
        fields:
          - label: "Title"
            name: "title"
            widget: string
          - label: "Images"
            name: "images"
            file: "_data/home-images.yml"
            widget: list
            fields:
              - {label: "Title", name: "title", widget: text}
              - {label: "Image File", name: "image", widget: text}
